language: ruby
sudo: false
cache: bundler

rvm:
- 2.5
- 2.4
- 2.3

gemfile:
- Gemfile.rails52
- Gemfile.rails51
- Gemfile.rails50
- Gemfile.rails42

jobs:
  include:
      rvm: 2.5
      gemfile: Gemfile
      script: bundle exec rubocop --parallel

notifications:
  email:
    on_success: never
    on_failure: always
